esphome:
  name: debug-test
  friendly_name: "Debug Test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

external_components:
  - source: my_components
    components: [ test_pwm ]

output:
  - platform: test_pwm
    id: debug_pwm
    pin: GPIO1
    frequency: 50000Hz
    driver: auto