esphome:
  name: mcpwm-minimal-test
  friendly_name: "MCPWM Minimal Test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# External components
external_components:
  - source: my_components
    components: [ mcpwm_unified ]

# Test single output
output:
  - platform: mcpwm_unified
    id: test_pwm
    pin: GPIO1
    frequency: 50000Hz